# Change these first
owner: tubirbutier # Your GitHub organization or username, where this repository lives
repo: hillside-status # The name of this repository

sites:
  - name: Hillside Technologies
    url: https://www.hillsidetechnologies.org/
  - name: Castorlist
    url: https://www.castorlist.qzz.io
  - name: "tubirbutier\'s personal site"
    url: https://www.tubirbutier.qzz.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hillsidetechnologies.org
  # baseUrl: /your-repo-name
  logoUrl: https://www.hillsidetechnologies.org/assets/images/Hillside2_200px.png
  name: Hillside Technologies
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Welcome. This status page is for all Hosted by Hillside sites & services.
  navbar:
    - title: Status
      href: /
    - title: Hillside Technologies
      href: https://www.hillsidetechnologies.org/
    - title: Castorlist
      href: https://www.castorlist.qzz.io
    - title: "tubirbutier\'s personal site"
      href: https://www.tubirbutier.qzz.io
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
