# Change these first
owner: tubirbutier # Your GitHub organization or username, where this repository lives
repo: hillside-status # The name of this repository

sites:
  - name: Hillside Technologies
    url: https://www.hillsidetechnologies.org/
  - name: Castorlist
    url: https://www.castorlist.qzz.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hillsidetechnologies.org
  # baseUrl: /your-repo-name
  logoUrl: https://www.hillsidetechnologies.org/assets/images/Hillside2_200px.png
  name: Hillside Technologies
  introTitle: "Hillside Status"
  introMessage: Welcome. This status page is for all Hosted by Hillside sites & services.
  navbar:
    - title: Status
      href: /
    - title: Hillside Technologies
      href: https://status.hillsidetechnologies.org/history/hillside-technologies
    - title: Castorlist
      href: https://status.hillsidetechnologies.org/history/castorlist
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
